version: 2

project_name: dizz

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: dizz
    main: .
    dir: .
    binary: dizz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/TheShiveshNetwork/dizz/cmd.version={{ .Version }}
    ignore:
      - goos: windows
        goarch: arm64

  - id: dizzie
    main: .
    dir: tui
    binary: dizzie
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [binary]
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: TheShiveshNetwork
    name: dizz

